// <auto-generated />
using System;
using BitNow_Backend.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitNow_Backend.DAL.Migrations
{
    [DbContext(typeof(BidNowDbContext))]
    [Migration("20251121122055_AddPausedAtToAuction")]
    partial class AddPausedAtToAuction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BidCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("bid_count");

                    b.Property<decimal?>("BuyNowPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("buy_now_price");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("CurrentBid")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("current_bid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("starting_bid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("PK__Auctions__3213E83F5033A638");

                    b.HasIndex("ItemId");

                    b.HasIndex("SellerId");

                    b.HasIndex("WinnerId");

                    b.HasIndex(new[] { "Status" }, "idx_auctions_status");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.AuctionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("FinalBid")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("final_bid");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("starting_bid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalBids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_bids");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("PK__AuctionH__3213E83F8F90DB51");

                    b.HasIndex(new[] { "SellerId" }, "idx_history_seller");

                    b.HasIndex(new[] { "WinnerId" }, "idx_history_winner");

                    b.ToTable("AuctionHistory", (string)null);
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.AutoBid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("max_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__AutoBids__3213E83FE492B6C8");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AuctionId", "UserId" }, "UQ__AutoBids__C46C653189F6A89F")
                        .IsUnique();

                    b.ToTable("AutoBids");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<DateTime?>("BidTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("bid_time")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("bidder_id");

                    b.Property<bool?>("IsAutoBid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_auto_bid");

                    b.HasKey("Id")
                        .HasName("PK__Bids__3213E83F55D6A6DC");

                    b.HasIndex(new[] { "AuctionId" }, "idx_bids_auction");

                    b.HasIndex(new[] { "BidderId" }, "idx_bids_bidder");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3213E83F277DE0DA");

                    b.HasIndex(new[] { "Slug" }, "UQ__Categori__32DD1E4CD9936ABD")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_reply");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__ContactM__3213E83FBD190A4F");

                    b.HasIndex("UserId");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.FavoriteSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.HasKey("Id")
                        .HasName("PK__Favorite__3213E83FB7177F4E");

                    b.HasIndex("SellerId");

                    b.HasIndex(new[] { "BuyerId", "SellerId" }, "UQ__Favorite__DD51D1FAAF26F0F0")
                        .IsUnique();

                    b.HasIndex(new[] { "BuyerId" }, "idx_favorites_buyer");

                    b.ToTable("FavoriteSellers");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("condition");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Items__3213E83FB79E5DB3");

                    b.HasIndex(new[] { "CategoryId" }, "idx_items_category");

                    b.HasIndex(new[] { "SellerId" }, "idx_items_seller");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__Messages__3213E83FCD78A6BD");

                    b.HasIndex("AuctionId");

                    b.HasIndex(new[] { "ReceiverId" }, "idx_messages_receiver");

                    b.HasIndex(new[] { "SenderId" }, "idx_messages_sender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("link");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3213E83F0684F1AC");

                    b.HasIndex(new[] { "UserId" }, "idx_notifications_user");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RatedId")
                        .HasColumnType("int")
                        .HasColumnName("rated_id");

                    b.Property<int>("RaterId")
                        .HasColumnType("int")
                        .HasColumnName("rater_id");

                    b.Property<int>("Rating1")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("PK__Ratings__3213E83F00FD3E6D");

                    b.HasIndex("RaterId");

                    b.HasIndex(new[] { "AuctionId", "RaterId", "RatedId" }, "UQ__Ratings__6384321E0C855D8C")
                        .IsUnique();

                    b.HasIndex(new[] { "RatedId" }, "idx_ratings_rated");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<decimal?>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("reputation_score");

                    b.Property<int?>("TotalPurchases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_purchases");

                    b.Property<int?>("TotalRatings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_ratings");

                    b.Property<int?>("TotalSales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_sales");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83FD002142C");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164AD34E528")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3213E83F823847CC");

                    b.HasIndex(new[] { "UserId", "Role" }, "UQ__UserRole__31DDE51AC6C34E00")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_roles_user");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Watchlis__3213E83F49C30639");

                    b.HasIndex("AuctionId");

                    b.HasIndex(new[] { "UserId", "AuctionId" }, "UQ__Watchlis__AB414F6AC4A841B0")
                        .IsUnique();

                    b.ToTable("Watchlist", (string)null);
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Auction", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Item", "Item")
                        .WithMany("Auctions")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Auctions__item_i__534D60F1");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Seller")
                        .WithMany("AuctionSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK__Auctions__seller__5441852A");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Winner")
                        .WithMany("AuctionWinners")
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("FK__Auctions__winner__5535A963");

                    b.Navigation("Item");

                    b.Navigation("Seller");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.AutoBid", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Auction", "Auction")
                        .WithMany("AutoBids")
                        .HasForeignKey("AuctionId")
                        .IsRequired()
                        .HasConstraintName("FK__AutoBids__auctio__60A75C0F");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "User")
                        .WithMany("AutoBids")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AutoBids__user_i__619B8048");

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Bid", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .IsRequired()
                        .HasConstraintName("FK__Bids__auction_id__59FA5E80");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .IsRequired()
                        .HasConstraintName("FK__Bids__bidder_id__5AEE82B9");

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.ContactMessage", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.User", "User")
                        .WithMany("ContactMessages")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ContactMe__user___73BA3083");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.EmailVerification", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.FavoriteSeller", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.User", "Buyer")
                        .WithMany("FavoriteSellerBuyers")
                        .HasForeignKey("BuyerId")
                        .IsRequired()
                        .HasConstraintName("FK__FavoriteS__buyer__00200768");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Seller")
                        .WithMany("FavoriteSellerSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK__FavoriteS__selle__01142BA1");

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Item", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Items__category___4D94879B");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Seller")
                        .WithMany("Items")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK__Items__seller_id__4CA06362");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Message", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Auction", "Auction")
                        .WithMany("Messages")
                        .HasForeignKey("AuctionId")
                        .HasConstraintName("FK__Messages__auctio__6E01572D");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__receiv__6D0D32F4");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__sender__6C190EBB");

                    b.Navigation("Auction");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Notification", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__user___05D8E0BE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Rating", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Auction", "Auction")
                        .WithMany("Ratings")
                        .HasForeignKey("AuctionId")
                        .IsRequired()
                        .HasConstraintName("FK__Ratings__auction__797309D9");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Rated")
                        .WithMany("RatingRateds")
                        .HasForeignKey("RatedId")
                        .IsRequired()
                        .HasConstraintName("FK__Ratings__rated_i__7B5B524B");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "Rater")
                        .WithMany("RatingRaters")
                        .HasForeignKey("RaterId")
                        .IsRequired()
                        .HasConstraintName("FK__Ratings__rater_i__7A672E12");

                    b.Navigation("Auction");

                    b.Navigation("Rated");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.UserRole", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__user___4316F928");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Watchlist", b =>
                {
                    b.HasOne("BitNow_Backend.DAL.Models.Auction", "Auction")
                        .WithMany("Watchlists")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Watchlist__aucti__6754599E");

                    b.HasOne("BitNow_Backend.DAL.Models.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Watchlist__user___66603565");

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Auction", b =>
                {
                    b.Navigation("AutoBids");

                    b.Navigation("Bids");

                    b.Navigation("Messages");

                    b.Navigation("Ratings");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.Item", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("BitNow_Backend.DAL.Models.User", b =>
                {
                    b.Navigation("AuctionSellers");

                    b.Navigation("AuctionWinners");

                    b.Navigation("AutoBids");

                    b.Navigation("Bids");

                    b.Navigation("ContactMessages");

                    b.Navigation("FavoriteSellerBuyers");

                    b.Navigation("FavoriteSellerSellers");

                    b.Navigation("Items");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Notifications");

                    b.Navigation("RatingRateds");

                    b.Navigation("RatingRaters");

                    b.Navigation("UserRoles");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
